apiVersion: v1
kind: LimitRange
metadata:
  name: lab10-limits
spec:
  limits:
    - type: Container
      default:
        cpu: "500m"
        memory: "128Mi"
      defaultRequest:
        cpu: "250m"
        memory: "64Mi"
      max:
        cpu: "1000m"
        memory: "512Mi"