apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab04-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lab04-nginx
  template:
    metadata:
      labels:
        app: lab04-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80