apiVersion: v1
kind: Pod
metadata:
  name: lab02-failing
  labels:
    app: failing
spec:
  containers:
    - name: failing-container
      image: nginx:alpine
      command: ["sh", "-c", "echo 'starting...' && exit 1"]